# Generated by Django 2.2.5 on 2019-10-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('userNo', models.IntegerField()),
                ('FileName', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='tanuki')),
                ('FilePath', models.CharField(default='none', max_length=40)),
                ('cate', models.CharField(default='other', max_length=2)),
                ('sub', models.CharField(default='other', max_length=2)),
                ('color', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
