# Generated by Django 2.2.5 on 2019-11-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=100, verbose_name='名前')),
                ('sex', models.CharField(default='none', max_length=10, verbose_name='性別')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('type', models.CharField(default='none', max_length=30, verbose_name='タイプ')),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(max_length=30, verbose_name='サブ１')),
                ('sub2', models.CharField(max_length=30, verbose_name='サブ２')),
            ],
            options={
                'db_table': 'BlackList',
            },
        ),
        migrations.CreateModel(
            name='Codnate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(max_length=30, null=True, verbose_name='サブ1')),
                ('sub2', models.CharField(max_length=30, null=True, verbose_name='サブ2')),
                ('sub3', models.CharField(max_length=30, null=True, verbose_name='サブ3')),
                ('sub4', models.CharField(max_length=30, null=True, verbose_name='サブ4')),
                ('sub5', models.CharField(max_length=30, null=True, verbose_name='サブ5')),
            ],
            options={
                'db_table': 'Codnate',
            },
        ),
        migrations.CreateModel(
            name='Color_type_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, verbose_name='色')),
                ('type', models.CharField(max_length=30, verbose_name='タイプ')),
            ],
            options={
                'db_table': 'Color_type_value',
            },
        ),
        migrations.CreateModel(
            name='Sub_type_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=30, verbose_name='サブ')),
                ('type1', models.CharField(max_length=30, null=True, verbose_name='タイプ1')),
                ('type2', models.CharField(max_length=30, null=True, verbose_name='タイプ2')),
            ],
            options={
                'db_table': 'Sub_type_value',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userNo', models.IntegerField(verbose_name='ユーザーNo')),
                ('FileName', models.CharField(default='none', max_length=40, verbose_name='ファイル名')),
                ('file', models.ImageField(upload_to='tanuki', verbose_name='ファイル')),
                ('FilePath', models.CharField(default='none', max_length=100, verbose_name='ファイルパス')),
                ('cate', models.CharField(default='other', max_length=30, verbose_name='カテゴリ')),
                ('sub', models.CharField(default='other', max_length=30, verbose_name='サブカテゴリ')),
                ('color', models.CharField(default='other', max_length=30, verbose_name='色')),
                ('color_type_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanuki.Color_type_value')),
                ('sub_type_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanuki.Sub_type_value')),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
    ]
