# Generated by Django 2.2.5 on 2019-10-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanuki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='cate',
            field=models.CharField(default='other', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sub',
            field=models.CharField(default='other', max_length=10),
        ),
    ]
