# Generated by Django 2.2.5 on 2019-10-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanuki', '0002_auto_20191027_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='FilePath',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
